eMarketStall/config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  resources :products do
    collection do
      get :search
    end
  end

  get 'wishlists/:id/add' => "wishlist_items#add", as: "add_to_wishlist"
  get 'wishlists/:id' => "wishlists#show", as: "show_wishlist"
  delete 'wishlist_items/:id' => "wishlist_items#remove", as: "remove_from_wishlist"

  post 'orders/create' => "orders#create", as: "orders_create"
  get 'orders/success' => "orders#success", as: "payment_success"
  get 'orders/cancel' => "orders#cancel", as: "payment_cancel"

  get 'carts/:cart_id' => "carts#show", as: "cart"
  delete 'carts/:cart_id' => "carts#destroy"

  post 'cart_items/:cart_item_id/increment' => "cart_items#increment_number", as: "cart_item_increase"
  post 'cart_items/:cart_item_id/decrease' => "cart_items#decrease_number", as: "cart_item_decrease"
  post 'cart_items' => "cart_items#create"
  get 'cart_items/:cart_item_id' => "cart_items#show", as: "cart_item"
  delete 'cart_items/:cart_item_id' => "cart_items#destroy"
  
  #only: [] to generate just routes for products
  #users routes handled by devise
  resources :users, only: [] do
    resources :products
    get 'my_products', to: 'users#my_products'
  end

  resources :products, only: [] do
    resources :reviews, except: :update
  end

  resources :users, only: [] do
    resources :orders, only: [:index]
  end
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 

  patch '/products/:product_id/reviews/:id', to: 'reviews#update', as: 'personalized_product_review'
  get '/user_reviews/:user_id', to: 'reviews#user_reviews', as: 'user_reviews'

  devise_scope :user do  
    get 'my_profile', to: 'users/registrations#show', as: :my_profile
    get '/users/sign_out' => 'devise/sessions#destroy'  
    get 'edit_profile', to: 'users/registrations#edit_profile'
    patch 'update_profile', to: 'users/registrations#update_profile'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

eMarketStall/app/models/order.rb
class Order < ApplicationRecord
    belongs_to :cart
    belongs_to :user
end

eMarketStall/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @user_for_orders = User.find(params[:user_id])
  end

  def show
    @order = Order.find(params[:id])
  end

  def success
    session_id = params[:session_id]
    if !session_id.nil? 
      @current_cart.decrease_quantity
      order = Order.create(user: @current_user, cart:@current_cart)
      order.save
      #after an order has completed, we create another cart
      session[:cart_id] = nil
      @success_session = Stripe::Checkout::Session.retrieve(id: params[:session_id], expand: ['line_items'])
    else
      redirect_to cancel_url(session_id: session_id), alert: "No info to display"
    end
  end

  def cancel
    @cancel_session = Stripe::Checkout::Session.retrieve(id: params[:session_id], expand: ['line_items'])
  end

  def create
    line_items_json = @current_cart.cart_items.map do |item|
      { price: item.product.stripe_price_id, quantity: item.quantity}
    end

    @session = Stripe::Checkout::Session.create({
        customer: @current_user.stripe_customer_id,
        payment_method_types: ['card', 'paypal', 'alipay'],
        line_items: line_items_json,
        mode: 'payment',
        success_url: payment_success_url + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url: payment_cancel_url + "?session_id={CHECKOUT_SESSION_ID}",
    })
    redirect_to @session.url
  end
  
  private
    
end

eMarketStall/app/helpers/orders_helper.rb
module OrdersHelper
end

eMarketStall/app/views/orders/cancel.html.erb
<div class="container">
  <h1 style="color:red;font-family: 'Poppins', sans-serif; font-weight: 500;">Checkout status: <%= @cancel_session.payment_status %>. Try again!</h1>
  <h3 style="font-family: 'Poppins', sans-serif; font-weight: 300;">Order subtotal: <%= @cancel_session.amount_total/100.to_f %> <%= @cancel_session.currency %></h3>
  <h5 class="card-title"></h5>
<% @cancel_session.line_items.data.each do |line_item| %>
    <% product = Product.find_by(stripe_product_id: line_item.price.product) %>
    <div class="card">
      <div class="row no-gutters">
        <div class="col-md-4">
          <%= image_tag(product.thumbnail(0), class: "card-img") %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title text-center"><%= product.title %></h5>
            <p class="card-text text-center"><%= product.description %></p>
            <p class="card-text text-center"><%= line_item.price.unit_amount/100.to_f %> <%= line_item.price.currency.upcase %></p>
          </div>
        </div>
      </div>
    </div>
<% end %>
</div>

eMarketStall/app/views/orders/index.html.erb
<h1 class="text-center mb-4" style="font-family: 'Poppins', sans-serif; font-weight: 700;">My orders</h1>

<% if @user_for_orders.orders.empty? %>
  <div class="alert alert-warning mt-3">
    <h6 class="font-weight-bolder">Your order list is empty</h6>
    <p><%= link_to 'Check products added to your cart', cart_path(@current_cart) %>
  </div>
<% else %>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col"><h5 style="font-family: 'Poppins', sans-serif; font-weight: 600;">Order ID</h5></th>
      <th scope="col"><h5 style="font-family: 'Poppins', sans-serif; font-weight: 600;">Product name</h5></th>
      <th scope="col"><h5 style="font-family: 'Poppins', sans-serif; font-weight: 600;">Price</h5></th>
      <th scope="col"><h5 style="font-family: 'Poppins', sans-serif; font-weight: 600;">Quantity</h5></th>
      <th scope="col"><h5 style="font-family: 'Poppins', sans-serif; font-weight: 600;">Order date</h5></th>
      <th scope="col"><h5 style="font-family: 'Poppins', sans-serif; font-weight: 600;"></h5></th>
    </tr>
  </thead>
  <tbody>
<% @user_for_orders.orders.sort_by { |order| order.created_at }.reverse.each do |order| %>
      <% order.cart.cart_items.each do |cart_item| %>
          <tr>
            <td><h6 style="font-family: 'Poppins', sans-serif; font-weight: 300;"><%= order.id %></h6></td> 
            <td><h6> <%= link_to cart_item.product.title, product_path(cart_item.product)%></h6></td> 
            <td><h6><%= cart_item.product.price %> eur</h6></td>
            <td><h6><%= cart_item.quantity %></h6></td>
            <td><h6><%= order.created_at.strftime("%d/%m/%Y") %></h6></td>
            <% if cart_item.product.reviews.exists?(user_id: @current_user.id) %>
              <% review = cart_item.product.reviews.find_by(user_id: @current_user.id) %>
              <td><%= link_to 'Update your opinion', edit_product_review_path(review.product_id, review.id), class: 'btn btn-warning' %></td>
            <% else %>
              <td><%= link_to 'Leave a review', new_product_review_path(:current_user_id => @current_user.id, :product_id => cart_item.product.id), class: 'btn btn-info text-white' %></td>
            <% end %>
          </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

eMarketStall/app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

eMarketStall/app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

eMarketStall/app/views/orders/success.html.erb
<div class="container">
  <h1 style="color:green">Order succesfully completed! That's a recap:</h1>
  <p style="font-size:15px">Amount paid: <%= @success_session.amount_total/100.to_f %> <%= @success_session.currency %></p>
<% @success_session.line_items.data.each do |line_item| %>
        <% product = Product.find_by(stripe_product_id: line_item.price.product) %>

        <div class="card">
          <div class="row no-gutters">
            <div class="col-md-4">
              <%= image_tag(product.thumbnail(0), class: "card-img") %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title text-center"><%= product.title %></h5>
                <p class="card-text text-center"><%= product.description %></p>
                <p class="card-text text-center"><%= line_item.price.unit_amount/100.to_f %> <%= line_item.price.currency.upcase %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>