eMarketStall/config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  resources :products do
    collection do
      get :search
    end
  end

  get 'wishlists/:id/add' => "wishlist_items#add", as: "add_to_wishlist"
  get 'wishlists/:id' => "wishlists#show", as: "show_wishlist"
  delete 'wishlist_items/:id' => "wishlist_items#remove", as: "remove_from_wishlist"

  post 'orders/create' => "orders#create", as: "orders_create"
  get 'orders/success' => "orders#success", as: "payment_success"
  get 'orders/cancel' => "orders#cancel", as: "payment_cancel"

  get 'carts/:cart_id' => "carts#show", as: "cart"
  delete 'carts/:cart_id' => "carts#destroy"

  post 'cart_items/:cart_item_id/increment' => "cart_items#increment_number", as: "cart_item_increase"
  post 'cart_items/:cart_item_id/decrease' => "cart_items#decrease_number", as: "cart_item_decrease"
  post 'cart_items' => "cart_items#create"
  get 'cart_items/:cart_item_id' => "cart_items#show", as: "cart_item"
  delete 'cart_items/:cart_item_id' => "cart_items#destroy"
  
  #only: [] to generate just routes for products
  #users routes handled by devise
  resources :users, only: [] do
    resources :products
    get 'my_products', to: 'users#my_products'
  end

  resources :products, only: [] do
    resources :reviews, except: :update
  end

  resources :users, only: [] do
    resources :orders, only: [:index]
  end
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 

  patch '/products/:product_id/reviews/:id', to: 'reviews#update', as: 'personalized_product_review'
  get '/user_reviews/:user_id', to: 'reviews#user_reviews', as: 'user_reviews'

  devise_scope :user do  
    get 'my_profile', to: 'users/registrations#show', as: :my_profile
    get '/users/sign_out' => 'devise/sessions#destroy'  
    get 'edit_profile', to: 'users/registrations#edit_profile'
    patch 'update_profile', to: 'users/registrations#update_profile'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

eMarketStall/app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items, dependent: :destroy
    has_many :products, through: :cart_items

    #called after an order ha succeeded to update products availability
    def decrease_quantity
      self.cart_items.each do |cart_item|
        selected_quantity = cart_item.quantity
        cart_item.product.availability -= selected_quantity
        cart_item.product.save
      end
    end

    def sub_total
        sum = 0
          self.cart_items.each do |cart_el|
            if !cart_el.product.nil?
              sum+= cart_el.total_price
            end
              
          end
        return sum
    end
end

eMarketStall/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :checks_oauth
  def show
    @cart = @current_cart
  end


  #destroying a cart, in our app means that session[:cart_id] has to be set up to nil
  #this will trigger in ApplicationController (method set_current_cart:line 14) the creation of a new cart, which initially will be empty
  def destroy
    session[:cart_id] = nil
    redirect_to cart_path(@current_cart)
  end

  private

  def checks_oauth
    if @current_user.città.blank? || @current_user.cap_residenza.blank? || @current_user.via_residenza.blank? || @current_user.num_telefono.blank?
      redirect_to edit_profile_path
      flash[:alert] = "To complete a purchase, additional information beyond what is provided by your OAuth provider is required."
    end
  end
end

eMarketStall/app/helpers/carts_helper.rb
module CartsHelper
end

eMarketStall/app/views/carts/show.html.erb
<h1 class="text-center" style="font-family: 'Poppins', sans-serif; font-weight: 700;">My cart</h1>
<% if @cart.cart_items.size == 0%>
  <div class="alert alert-warning mt-3">
    <h3 class="font-weight-bolder">Your cart is empty</h3>
    <%= link_to "add products", products_path %>
  </div>
<%else%>
<h3>Your cart contains:</h3>
<br>
  <% @cart.cart_items.each do |cart_el| %>
    <div class="row">
      <div class="col-md-12 d-flex justify-content-center">
        <div class="card" style="width: 100%;">
          <div class="row align-items-center">
            <div class="col-md-4">
              <div class="p-4">
                <%= image_tag(cart_el.product.thumbnail(0)) %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card-body">
                <% if cart_el.product.verified == false %>
                  <div class="alert alert-danger mt-3">
                    <h5 style="font-family: 'Poppins', sans-serif; font-weight: 500;">This product has not been verified by an admin yet. This means that there is no quality assurance for the listing.</h5>
                  </div>
                <% end %>
                <div>
                  <h1 class="card-title" style="font-family: 'Poppins', sans-serif; font-weight: 400;"><%= link_to cart_el.product.title, cart_el %>
                  <h5 class="card-text" style="font-family: 'Poppins', sans-serif; font-weight: 300;">x <%= cart_el.quantity %></h5>
                  <h3 class="card-text" style="font-family: 'Poppins', sans-serif; font-weight: 300;"><%= cart_el.product.description %></h3>
                  <h2 class="card-text" style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= "€"+cart_el.product.price.to_s+"0" %></h2>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <div class="card-body d-flex flex-column justify-content-end align-items-center">
                <div>
                  <%= link_to cart_item_increase_path(cart_item_id: cart_el), id: 'add-one', method: :post do %>
                    <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#242424}</style><path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32V224H48c-17.7 0-32 14.3-32 32s14.3 32 32 32H192V432c0 17.7 14.3 32 32 32s32-14.3 32-32V288H400c17.7 0 32-14.3 32-32s-14.3-32-32-32H256V80z"/></svg>
                  <% end %>
                  <br>
                  <br>
                  <%= link_to cart_item_decrease_path(cart_item_id: cart_el), id: 'remove-one', method: :post do %>
                    <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#242424}</style><path d="M432 256c0 17.7-14.3 32-32 32L48 288c-17.7 0-32-14.3-32-32s14.3-32 32-32l352 0c17.7 0 32 14.3 32 32z"/></svg>
                  <% end %>
                  <br>
                  <br>
                  <%= link_to cart_item_path(cart_el), method: :delete do %>
                    <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 448 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#242424}</style><path d="M135.2 17.7C140.6 6.8 151.7 0 163.8 0H284.2c12.1 0 23.2 6.8 28.6 17.7L320 32h96c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 96 0 81.7 0 64S14.3 32 32 32h96l7.2-14.3zM32 128H416V448c0 35.3-28.7 64-64 64H96c-35.3 0-64-28.7-64-64V128zm96 64c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16zm96 0c-8.8 0-16 7.2-16 16V432c0 8.8 7.2 16 16 16s16-7.2 16-16V208c0-8.8-7.2-16-16-16z"/></svg>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<br>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>

<!-- See Order section below for explanation of new_order_path -->
<%= button_to "Proceed to checkout", orders_create_path, class: "btn btn-primary" %><br>

<%= link_to "Empty cart", cart_path(@current_cart), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger text-white" %>
<%end%>