eMarketStall/config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  resources :products do
    collection do
      get :search
    end
  end

  get 'wishlists/:id/add' => "wishlist_items#add", as: "add_to_wishlist"
  get 'wishlists/:id' => "wishlists#show", as: "show_wishlist"
  delete 'wishlist_items/:id' => "wishlist_items#remove", as: "remove_from_wishlist"

  post 'orders/create' => "orders#create", as: "orders_create"
  get 'orders/success' => "orders#success", as: "payment_success"
  get 'orders/cancel' => "orders#cancel", as: "payment_cancel"

  get 'carts/:cart_id' => "carts#show", as: "cart"
  delete 'carts/:cart_id' => "carts#destroy"

  post 'cart_items/:cart_item_id/increment' => "cart_items#increment_number", as: "cart_item_increase"
  post 'cart_items/:cart_item_id/decrease' => "cart_items#decrease_number", as: "cart_item_decrease"
  post 'cart_items' => "cart_items#create"
  get 'cart_items/:cart_item_id' => "cart_items#show", as: "cart_item"
  delete 'cart_items/:cart_item_id' => "cart_items#destroy"
  
  #only: [] to generate just routes for products
  #users routes handled by devise
  resources :users, only: [] do
    resources :products
    get 'my_products', to: 'users#my_products'
  end

  resources :products, only: [] do
    resources :reviews, except: :update
  end

  resources :users, only: [] do
    resources :orders, only: [:index]
  end
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 

  patch '/products/:product_id/reviews/:id', to: 'reviews#update', as: 'personalized_product_review'
  get '/user_reviews/:user_id', to: 'reviews#user_reviews', as: 'user_reviews'

  devise_scope :user do  
    get 'my_profile', to: 'users/registrations#show', as: :my_profile
    get '/users/sign_out' => 'devise/sessions#destroy'  
    get 'edit_profile', to: 'users/registrations#edit_profile'
    patch 'update_profile', to: 'users/registrations#update_profile'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

eMarketStall/app/models/product.rb
class Product < ApplicationRecord
    # Associazioni
  has_many_attached :images, :dependent => :destroy
  has_many :reviews, :dependent => :destroy
  belongs_to :user
  after_create :set_stripe_product_id
  #only if price changed
  after_update :update_stripe_price_obj, if: :saved_change_to_price?

  before_validation :set_published_at, on: :create
  before_create :set_unverified

  # Validazioni
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :category, inclusion: { in: ['Chains', 'Vases', 'Painting', 'Plates', 'Wood processing'] }
  validates :availability, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :published_at, presence: true

  def thumbnail(i)
    return self.images[i].variant(resize: '300x300').processed
  end

  def thumbnail_bigger(i)
      self.images[i].variant(resize: '500x500').processed
  end

  def thumbnail_small(i)
    self.images[i].variant(resize: '150x150').processed
end

  private

  def set_published_at
    self.published_at = Time.current
  end

  def set_stripe_product_id 
    product = Stripe::Product.create(name: self.title, description: self.description)
    # * 100 beceause Stipe amounts are in cents unit
    price = Stripe::Price.create(product: product, unit_amount: (self.price * 100).to_i, currency: 'eur')
    update(stripe_product_id: product.id, stripe_price_id: price.id)
  end

  #when prices changes, we need to create another price object
  def update_stripe_price_obj 
    price = Stripe::Price.create(product: self.stripe_product_id, unit_amount: (self.price * 100).to_i, currency: 'eur')
    # * 100 beceause Stipe amounts are in cents unit
    update(stripe_price_id: price.id)
  end

  def set_unverified
    self.verified = false
  end
end

eMarketStall/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authorize_product, only: [:edit, :update, :destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
    @searched_item=params[:search]
    @category=params[:category]
    @products=Product.where("title LIKE ?", "%#{@searched_item}%")
    if @category.present?
      @products=@products.where(category: @category)
    end
    if params[:sort]=="Title"
      @products=Product.order(:title)
    elsif params[:sort]=="Price"
      @products=Product.order(:price)
    end
  end

  # GET /products/1 or /products/1.json
  def show
    @user = current_user
    @product = Product.find(params[:id])
    @num_reviews = Review.where(product_id: @product.id).count
  end

  # GET /products/new
  def new
    @user = current_user
    @product = @user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @user = current_user
    @product = @user.products.build(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    authorize! :update, @product
    respond_to do |format|
      if @product.update(product_params)
        @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    authorize! :destroy, @product
    #I know, it's brutal but I had to add these two attributes to handle correctly a destruction from a seller of a product.
    #Did to resolve the following problem: When a seller removes a product from the database, it can create a problem with the foreign key constraint in the context
    #of orders. If a user has already purchased a product, but there are still remaining pieces of that product available for sale, the order associated with that
    #user would have a reference to the product. However, if the seller decides to remove the product from the database, the foreign key constraint would be violated
    # because the order would reference a non-existent product.
    @product.removed_from_seller = true;
    @product.removed_at= Date.today;
    @product.save

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :category, :availability, :verified, images: [])
    end

    def authorize_product
      authorize! params[:action].to_sym, @product, @current_user
    end
    
end

eMarketStall/app/helpers/products_helper.rb
module ProductsHelper
end

eMarketStall/app/views/products/_form.html.erb
<div class="container" style="margin-top: 2%;">
  <div class="row">
  <div class="col-lg-2">

  </div>
    <div class="col-lg-6">
      <%= form_with(model: product, class: "card") do |form| %>
        <div class= "card-title text-center ">
          <h1 class="font-weight-bold" style="font-family: 'Poppins', sans-serif; font-weight: 700;">Insert product details</h1>
        </div>
        <div class="card-body">
          <div class="form-group">
            <h6 style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= form.label :title %></h6>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <h6 style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= form.label :description %></h6>
            <%= form.text_area :description, class: "form-control" %>
          </div>

          <div class="form-group">
            <h6 style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= form.label :price %></h6>
            <%= form.text_field :price, class: "form-control" %>
          </div>

          <div class="form-group">
            <h6 style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= form.label :category %></h6>
            <%= form.select :category, options_for_select(["Chains", "Vases", "Painting", "Plates", "Wood processing"], product.category), { include_blank: true }, class: "form-control" %>
          </div>

          <div class="form-group">
            <h6 style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= form.label :availability %></h6>
            <%= form.number_field :availability, class: "form-control" %>
          </div>

          <div class="form-group">
            <h6 style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= form.label :images %></h6>
            <%= form.file_field :images, multiple: true, class: "form-control-file" %>
          </div>

          <% if can?(:manage, product) %>
            <div class="form-group">  
              <h6 style="font-family: 'Poppins', sans-serif; font-weight: 600;"><%= form.label :verified %></h6>
              <%= form.check_box :verified, checked: product.verified %>
            </div>
          <% end %>

        </div>

        <div class="card-footer text-center">
          <%= form.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-4">
      <% if product.errors.any? %>
          <div id="error_explanation">
            <h2 class="card-title">
              <%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:
            </h2>
            <ul class="list-unstyled">
              <% product.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
  </div>
  </div> 
</div>

eMarketStall/app/views/products/edit.html.erb
<%= render 'form', product: @product %>

eMarketStall/app/views/products/index.html.erb
<% if !current_user.roles_mask.nil? %>
<% if @current_user.roles_mask!=3 %>
<div class="alert alert-primary" style="width: 70%; margin-top: 1%">
  <% if @current_user.roles_mask==1 %>
    <h4 style="font-family: 'Poppins', sans-serif; font-weight: 500;">You are now a seller user. If you want to buy products you need to switch your role to buyer</h4>
  <% elsif @current_user.roles_mask==2 %>
    <h4 style="font-family: 'Poppins', sans-serif; font-weight: 500;">You are now a buyer user. If you want to sell products you need to switch your role to seller</h4>
  <% end %>
</div>
<% end %>
<% else %>
    <div class="alert alert-primary" style="width: 40%; margin-top: 1%">
      <h5 style="font-family: 'Poppins', sans-serif; font-weight: 500;">To maximize your experience, please update your profile data</h5>
    </div>
<% end %>
<h1 style="font-family: 'Poppins', sans-serif; font-weight: 700;">Products for sale</h1>

<%= form_with(url: products_path, method: "get", id: "search-form", class: "form-inline") do |f| %>
  <div class="input-group mb-3">
    <%= f.text_field :search, placeholder: "Search products...", class: "form-control", style: "width: 600px"%>
    <div class="input-group-append">
      <%= f.select :category, options_for_select(["Chains","Wood processing", "Plates", "Painting", "Vases"], params[:category]), {include_blank: "Category"}, id: "category-select", class: "custom-select" %>
    </div>
    <div class="input-group-append">
      <%= f.submit "Search", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<%= form_with(url: products_path, method: "get", id: "order-by", class: "form-inline") do |s| %>
  <div class="input-group mb-3">
    <%= s.select :sort, options_for_select(["Title", "Price"], params[:sort]), {include_blank: "Order by"}, id: "sort-select", class: "form-select" %>
  </div>
<% end %>

<% if @products.empty? %>
  <div class="alert alert-warning mt-3">
    <p class="font-weight-bolder">No products found</p>
  </div>
<% else %>
  <div class="container">
  <% @products.each do |product| %>
    <% if product.availability > 0 && product.user_id != @current_user.id && !product.removed_from_seller %>
    <div class="row">
      <div class="col-md-12 d-flex justify-content-center">
        <div class="card" style="width: 100%;">
          <div class="row align-items-center">
            <div class="col-md-4">
              <% if product.images.count==1 %>
                <div class="p-4">
                  <%= image_tag(product.thumbnail(0)) %>
                </div>
              <% elsif product.images.count>1 %>
                <div id="carousel" class="carousel p-4" data-ride="carousel" data-interval="false">
                  <ol class="carousel-indicators">
                    <li data-target="#carousel1" data-slide-to="0" class="active"></li>
                    <% for i in 2..product.images.count do %>
                      <li data-target=<% "#carousel"+i.to_s %> data-slide-to=<% (i-1).to_s %>></li>
                    <% end %>
                  </ol>
                  <div class="carousel-inner">
                    <div class="carousel-item active">
                      <%= image_tag(product.thumbnail(0)) %>
                    </div>
                    <% for i in 1...product.images.count do %>
                    <div class="carousel-item">
                      <%= image_tag(product.thumbnail(i)) %>
                    </div>
                    <% end %>
                  </div>
                  <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                  </a>
                </div>
              <% end %>
            </div>
            <div class="col-md-6">
              <div class="card-body">
                <div>
                  <h1 class="card-title" style="font-family: 'Poppins', sans-serif; font-weight: 400;"><%= link_to product.title, product %>    <% if product.verified %><span style="color: green; font-size: 40px;">&#x2713;</span><% end %></h1>
                  <h5 class="card-text" style="font-family: 'Poppins', sans-serif; font-weight: 300;"><%= product.description %></h5>
                  <h3 class="card-text"><%= "€"+product.price.to_s+"0" %></h3>
                  <% if product.availability <= 3 %>
                    <p style="color: red;font-family: 'Poppins', sans-serif; font-weight: 200;font-size: 20px;">Remaining: <%= product.availability.to_s %></p>
                  <% elsif  product.availability > 3 && product.availability < 8 %>
                    <p style="color: orange;font-family: 'Poppins', sans-serif; font-weight: 200;font-size: 20px;">Remaining: <%= product.availability.to_s %></p>
                  <% end %>
                </div>
              </div>
            </div>
            <% if can? :buy, product %>
            <div class="col-md-2">
              <div class="card-body d-flex flex-column justify-content-end align-items-center">
                <div>
                  <% if can? :manage, product %>
                    <%= link_to edit_product_path(product) do %>
                      <svg xmlns="http://www.w3.org/2000/svg" height="3em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><style>svg{fill:#242424}</style><path d="M410.3 231l11.3-11.3-33.9-33.9-62.1-62.1L291.7 89.8l-11.3 11.3-22.6 22.6L58.6 322.9c-10.4 10.4-18 23.3-22.2 37.4L1 480.7c-2.5 8.4-.2 17.5 6.1 23.7s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L387.7 253.7 410.3 231zM160 399.4l-9.1 22.7c-4 3.1-8.5 5.4-13.3 6.9L59.4 452l23-78.1c1.4-4.9 3.8-9.4 6.9-13.3l22.7-9.1v32c0 8.8 7.2 16 16 16h32zM362.7 18.7L348.3 33.2 325.7 55.8 314.3 67.1l33.9 33.9 62.1 62.1 33.9 33.9 11.3-11.3 22.6-22.6 14.5-14.5c25-25 25-65.5 0-90.5L453.3 18.7c-25-25-65.5-25-90.5 0zm-47.4 168l-144 144c-6.2 6.2-16.4 6.2-22.6 0s-6.2-16.4 0-22.6l144-144c6.2-6.2 16.4-6.2 22.6 0s6.2 16.4 0 22.6z"/></svg>
                    <% end %>
                    <br>
                    <br>
                  <% end %>
                  <%= link_to cart_items_path(:product_id => product.id), id: "cart-link", method: :post do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" id="cart"><path fill="none" d="M0 0h48v48H0zm36.62 12L31.1 22z"></path><path d="M22 18h4v-6h6V8h-6V2h-4v6h-6v4h6v6zm-8 18c-2.21 0-3.98 1.79-3.98 4s1.77 4 3.98 4 4-1.79 4-4-1.79-4-4-4zm20 0c-2.21 0-3.98 1.79-3.98 4s1.77 4 3.98 4 4-1.79 4-4-1.79-4-4-4zm-19.65-6.5c0-.09.02-.17.06-.24l1.8-3.26h14.9c1.5 0 2.81-.83 3.5-2.06l7.72-14.02L38.83 8h-.01l-2.21 4-5.51 10H17.07l-.26-.54L12.32 12l-1.9-4-1.89-4H2v4h4l7.2 15.17-2.71 4.9c-.31.58-.49 1.23-.49 1.93 0 2.21 1.79 4 4 4h24v-4H14.85c-.28 0-.5-.22-.5-.5z"></path></svg>
                  <% end %>
                  <br>
                  <br>
                  <% wl_user=Wishlist.find_by(user_id: @current_user.id) %>
                  <% found=false %>
                  <% wl_user.wishlist_items.each do |wl_item| %>
                    <% if wl_item.product.id==product.id %>
                      <% found=true %>
                      <% break %>
                    <% end %>
                  <% end %>
                  <% if !found %>
                    <%= link_to add_to_wishlist_path(product.id) do %>
                      <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 512 512" id="heart"><path d="M349.6 64c-36.4 0-70.718 16.742-93.6 43.947C233.117 80.742 198.8 64 162.4 64 97.918 64 48 114.221 48 179.095c0 79.516 70.718 143.348 177.836 241.694L256 448l30.164-27.211C393.281 322.442 464 258.61 464 179.095 464 114.221 414.082 64 349.6 64zm-80.764 329.257l-4.219 3.873-8.617 7.773-8.616-7.772-4.214-3.869c-50.418-46.282-93.961-86.254-122.746-121.994C92.467 236.555 80 208.128 80 179.095c0-22.865 8.422-43.931 23.715-59.316C118.957 104.445 139.798 96 162.4 96c26.134 0 51.97 12.167 69.11 32.545L256 157.661l24.489-29.116C297.63 108.167 323.465 96 349.6 96c22.603 0 43.443 8.445 58.686 23.778C423.578 135.164 432 156.229 432 179.095c0 29.033-12.467 57.459-40.422 92.171-28.784 35.74-72.325 75.709-122.742 121.991z"></path></svg>
                    <% end %>
                  <% else %>
                    <%= link_to remove_from_wishlist_path(product.id), method: :delete do %>
                      <svg xmlns="http://www.w3.org/2000/svg" id="heart" x="0" y="0" version="1.1" viewBox="0 0 29 29" xml:space="preserve"><path d="m14.854 6.083-.354.353-.354-.354a6.5 6.5 0 0 0-9.192 9.192l.354.354L14.5 24.82l9.192-9.192.354-.354a6.5 6.5 0 0 0-9.192-9.191z"></path><path d="m14.854 6.083-.354.353-.354-.354a6.5 6.5 0 0 0-9.192 9.192l.354.354L14.5 24.82l9.192-9.192.354-.354a6.5 6.5 0 0 0-9.192-9.191z"></path></svg>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
  </div>
<% end %>

<script>
  document.addEventListener("turbolinks:load", function(){
    const select=document.getElementById("sort-select");
    select.addEventListener("change", function(){
      document.getElementById("order-by").submit();
    });
  });
</script>

eMarketStall/app/views/products/new.html.erb
<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>