eMarketStall/config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  get 'orders/show'
  get 'orders/new'
  get 'carts/show'
  resources :products do
    collection do
      get :search
    end
  end

  get 'wishlists/:id/add' => "wishlist_items#add", as: "add_to_wishlist"
  get 'wishlists/:id' => "wishlists#show", as: "show_wishlist"
  delete 'wishlist_items/:id' => "wishlist_items#remove", as: "remove_from_wishlist"

  post 'orders/create' => "orders#create", as: "orders_create"
  get 'orders/success' => "orders#success", as: "payment_success"
  get 'orders/cancel' => "orders#cancel", as: "payment_cancel"

  get 'carts/:cart_id' => "carts#show", as: "cart"
  delete 'carts/:cart_id' => "carts#destroy"

  post 'cart_items/:cart_item_id/increment' => "cart_items#increment_number", as: "cart_item_increase"
  post 'cart_items/:cart_item_id/decrease' => "cart_items#decrease_number", as: "cart_item_decrease"
  post 'cart_items' => "cart_items#create"
  get 'cart_items/:cart_item_id' => "cart_items#show", as: "cart_item"
  delete 'cart_items/:cart_item_id' => "cart_items#destroy"
  
  #only: [] to generate just routes for products
  #users routes handled by devise
  resources :users, only: [] do
    resources :products
    get 'my_products', to: 'users#my_products'
  end

  resources :products, only: [] do
    resources :reviews, except: :update
  end

  resources :users, only: [] do
    resources :orders, only: [:index]
  end
  
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  } 

  patch '/products/:product_id/reviews/:id', to: 'reviews#update', as: 'personalized_product_review'
  get '/user_reviews/:user_id', to: 'reviews#user_reviews', as: 'user_reviews'

  devise_scope :user do  
    get 'my_profile', to: 'users/registrations#show', as: :my_profile
    get '/users/sign_out' => 'devise/sessions#destroy'  
    get 'edit_profile', to: 'users/registrations#edit_profile'
    patch 'update_profile', to: 'users/registrations#update_profile'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"
end

eMarketStall/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EMarketStall</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- Icone Font-Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'nav' %>
    <%= javascript_pack_tag 'application' , 'data-turbolinks-track': 'reload'%>
    <%= stripe_javascript_tag%>
    <%= javascript_pack_tag 'form_controls' %>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Montserrat+Subrayada:wght@700&display=swap');
      @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap');
    </style>
    <style>
        .alert {
          padding: 12px;
          font-size: 15px;
          border-radius: 4px;
        }

        .alert-warning {
          padding: 12px;
          font-size: 17px;
          border-radius: 4px;
        }

        #alert{
          display: none;
        }
    </style>
  </head>

  <body>
  
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #8CC63F">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%= root_path %>" id="logo" style="font-family: 'Montserrat Subrayada', sans-serif;">EMarketStall</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <% if can? :see, Order %>
              <li class="nav-item mr-5">
                <%= link_to 'My orders', user_orders_path(@current_user), class: 'nav-link text-white' %>
              </li>
            <% end %>
            <% if can? :see, Cart %>
              <li class="nav-item mr-5">
                <%= link_to 'My cart', cart_path(@current_cart), class: 'nav-link text-white' %>
              </li>
            <% end %>
              <% if can? :see, Wishlist %>
                <li class="nav-item mr-5">
                <%= link_to 'My wishlist', show_wishlist_path(@current_user), class: 'nav-link text-white' %>
                </li>
              <% end %>
              <% if can? :see, Product %>
                <li class="nav-item mr-5">
                <%= link_to 'My products', user_my_products_path(current_user), class: 'nav-link text-white' %>
              </li>
              <% end %>
              <li class="nav-item mr-5">
                <%= link_to 'My profile', my_profile_path, class: 'nav-link text-white', id: "my-prfl" %>
              </li>
            <% end %>
            <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger text-white' %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <% if alert.present? %>
    <div class="alert alert-warning" style="width: 30%; margin-top: 3%">
      <div class="row">
        <div class="col-md-2">
          <svg xmlns="http://www.w3.org/2000/svg" height="2.5em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M256 512A256 256 0 1 0 256 0a256 256 0 1 0 0 512zm0-384c13.3 0 24 10.7 24 24V264c0 13.3-10.7 24-24 24s-24-10.7-24-24V152c0-13.3 10.7-24 24-24zM224 352a32 32 0 1 1 64 0 32 32 0 1 1 -64 0z"/></svg>  
        </div> 
        <div class="col-md-10"> 
          <%= alert %>
        </div>
      </div>
    </div>
  <% end %>
  <% if notice.present? %>
    <div class="alert alert-success" style="width: 30%; margin-top: 3%">
      <%= notice %>
    </div>
  <% end %>
  <%= yield %>
  </body>
</html>